 SELECT TABLE_NAME
FROM USER_TABLES
ORDER BY TABLE_NAME;

SELECT * FROM CUSTOMERS;

SELECT * FROM EMPLOYEES;

SELECT * FROM VEHICLES
WHERE STATUS='AVAILABLE';

SELECT
R.RENTAL_ID,
C.FIRST_NAME,
C.LAST_NAME,
R.RENTAL_DATE,
R.TOTAL_AMOUNT
FROM RENTALS R
JOIN CUSTOMERS C
ON R.CUSTOMER_ID=C.CUSTOMER_ID;

SELECT
P.PAYMENT_ID,
P.AMOUNT,
P.PAYMENT_METHOD,
R.RENTAL_ID
FROM PAYMENTS P
JOIN RENTALS R
ON P.RENTAL_ID=R.RENTAL_ID;

SELECT
VR.RETURN_ID,
VR.ACTUAL_RETURN_DATE,
VR.CONDITION_STATUS,
VR.REMARKS
FROM VEHICLE_RETURNS VR;

SELECT * FROM CUSTOMERS;

SELECT GET_TOTAL_RENTALS(1) AS TOTAL_RENTALS
FROM DUAL;

SELECT * FROM AUDIT_LOG;

SELECT * FROM USER_ERRORS
WHERE NAME = 'TRG_AUDIT_CUSTOMERS';

SELECT * FROM AUDIT_LOG;

SELECT * FROM VW_RENTAL_DETAILS;

SELECT RENTAL_SEQ.NEXTVAL FROM DUAL;
