 CREATE OR REPLACE PROCEDURE ADD_CUSTOMER(
    P_ID NUMBER,
    P_FIRST_NAME VARCHAR2,
    P_LAST_NAME VARCHAR2,
    P_PHONE VARCHAR2,
    P_EMAIL VARCHAR2,
    P_ADDRESS VARCHAR2
)
AS
BEGIN
    INSERT INTO CUSTOMERS
    VALUES(P_ID,P_FIRST_NAME,P_LAST_NAME,P_PHONE,P_EMAIL,P_ADDRESS);

    COMMIT;
END;
/

  CREATE OR REPLACE FUNCTION GET_TOTAL_RENTALS
(
    P_CUSTOMER_ID NUMBER
)
RETURN NUMBER
AS
    V_TOTAL NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_TOTAL
    FROM RENTALS
    WHERE CUSTOMER_ID = P_CUSTOMER_ID;

    RETURN V_TOTAL;
END;
/

  CREATE OR REPLACE PACKAGE CUSTOMER_PACKAGE AS
    PROCEDURE SHOW_CUSTOMERS;
END CUSTOMER_PACKAGE;
/

  CREATE OR REPLACE PACKAGE BODY CUSTOMER_PACKAGE AS

    PROCEDURE SHOW_CUSTOMERS
    AS
    BEGIN
        FOR C IN (SELECT * FROM CUSTOMERS) LOOP
            DBMS_OUTPUT.PUT_LINE(
                C.CUSTOMER_ID || ' - ' ||
                C.FIRST_NAME || ' ' ||
                C.LAST_NAME
            );
        END LOOP;
    END;

END CUSTOMER_PACKAGE;
/

  CREATE OR REPLACE TRIGGER TRG_AUDIT_CUSTOMERS
AFTER INSERT OR UPDATE OR DELETE
ON CUSTOMERS
FOR EACH ROW
BEGIN
    INSERT INTO AUDIT_LOG
    (
        TABLE_NAME,
        OPERATION,
        USER_NAME,
        ACTION_DATE
    )
    VALUES
    (
        'CUSTOMERS',
        CASE
            WHEN INSERTING THEN 'INSERT'
            WHEN UPDATING THEN 'UPDATE'
            WHEN DELETING THEN 'DELETE'
        END,
        USER,
        SYSDATE
    );
END;
/

  CREATE OR REPLACE TRIGGER TRG_AUDIT_CUSTOMERS
AFTER INSERT OR UPDATE OR DELETE
ON CUSTOMERS
FOR EACH ROW
DECLARE
    V_OPERATION VARCHAR2(20);
BEGIN
    IF INSERTING THEN
        V_OPERATION := 'INSERT';
    ELSIF UPDATING THEN
        V_OPERATION := 'UPDATE';
    ELSIF DELETING THEN
        V_OPERATION := 'DELETE';
    END IF;

    INSERT INTO AUDIT_LOG
    (
        TABLE_NAME,
        OPERATION,
        USER_NAME,
        ACTION_DATE
    )
    VALUES
    (
        'CUSTOMERS',
        V_OPERATION,
        USER,
        SYSDATE
    );
END;
/

  CREATE OR REPLACE TRIGGER TRG_SECURITY
BEFORE INSERT OR UPDATE OR DELETE
ON CUSTOMERS
DECLARE
    V_COUNT NUMBER;
BEGIN
    -- Block Monday to Friday
    IF TO_CHAR(SYSDATE,'DY','NLS_DATE_LANGUAGE=ENGLISH')
       IN ('MON','TUE','WED','THU','FRI') THEN
        RAISE_APPLICATION_ERROR(-20001,
        'Operations are not allowed from Monday to Friday.');
    END IF;

    -- Block public holidays
    SELECT COUNT(*)
    INTO V_COUNT
    FROM HOLIDAYS
    WHERE HOLIDAY_DATE = TRUNC(SYSDATE);

    IF V_COUNT > 0 THEN
        RAISE_APPLICATION_ERROR(-20002,
        'Operations are not allowed on public holidays.');
    END IF;
END;
/

  CREATE OR REPLACE VIEW VW_RENTAL_DETAILS AS
SELECT
    R.RENTAL_ID,
    C.FIRST_NAME || ' ' || C.LAST_NAME AS CUSTOMER_NAME,
    V.BRAND,
    V.MODEL,
    R.RENTAL_DATE,
    R.RETURN_DATE,
    R.TOTAL_AMOUNT
FROM RENTALS R
JOIN CUSTOMERS C ON R.CUSTOMER_ID = C.CUSTOMER_ID
JOIN VEHICLES V ON R.VEHICLE_ID = V.VEHICLE_ID;
