 DECLARE
    CURSOR VEHICLE_CURSOR IS
        SELECT BRAND, MODEL, DAILY_RATE
        FROM VEHICLES;

    V_BRAND VEHICLES.BRAND%TYPE;
    V_MODEL VEHICLES.MODEL%TYPE;
    V_RATE VEHICLES.DAILY_RATE%TYPE;

BEGIN
    OPEN VEHICLE_CURSOR;

    LOOP
        FETCH VEHICLE_CURSOR INTO V_BRAND, V_MODEL, V_RATE;
        EXIT WHEN VEHICLE_CURSOR%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE(
            V_BRAND || ' ' ||
            V_MODEL || ' - $' ||
            V_RATE
        );
    END LOOP;

    CLOSE VEHICLE_CURSOR;
END;
/

  DECLARE
    V_TOTAL NUMBER;
BEGIN
    SELECT TOTAL_AMOUNT
    INTO V_TOTAL
    FROM RENTALS
    WHERE RENTAL_ID = 100;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Rental not found.');
END;
/

  DECLARE
    CURSOR VEHICLE_CURSOR IS
        SELECT BRAND, MODEL, DAILY_RATE
        FROM VEHICLES;

    V_BRAND VEHICLES.BRAND%TYPE;
    V_MODEL VEHICLES.MODEL%TYPE;
    V_RATE VEHICLES.DAILY_RATE%TYPE;

BEGIN
    OPEN VEHICLE_CURSOR;

    LOOP
        FETCH VEHICLE_CURSOR INTO V_BRAND, V_MODEL, V_RATE;
        EXIT WHEN VEHICLE_CURSOR%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE(
            V_BRAND || ' ' ||
            V_MODEL || ' - $' ||
            V_RATE
        );
    END LOOP;

    CLOSE VEHICLE_CURSOR;
END;
/
